# Generated by Django 2.2.12 on 2021-05-26 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('cveMensaje', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=200)),
                ('fechaEnvio', models.DateField()),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Cuidador')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Especialista')),
            ],
        ),
    ]
