# Generated by Django 2.2.12 on 2021-05-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Especialista', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
