-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 21:33:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ESPECIALISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESPECIALISTA` (
  `nomUsuario` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(70) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(70) NOT NULL,
  `unidadMedica` VARCHAR(100) NOT NULL,
  `cedulaMedicaG` VARCHAR(8) NOT NULL,
  `Especialidad` VARCHAR(40) NULL,
  `numPacientes` INT NULL,
  PRIMARY KEY (`nomUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CUIDADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CUIDADOR` (
  `nomUsuario` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(70) NULL,
  `contraseña` VARCHAR(45) NULL,
  `correo` VARCHAR(70) NULL,
  PRIMARY KEY (`nomUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PACIENTE` (
  `nomUsuario` VARCHAR(20) NOT NULL,
  `especialista` VARCHAR(8) NOT NULL,
  `cuidador` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(70) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(70) NOT NULL,
  `escolaridad` ENUM('Ninguna', 'Primaria', 'Secundaria', 'Bachillerato', 'Licenciatura o superior') NOT NULL,
  `fechaNac` DATE NOT NULL,
  `sexo` ENUM('Femenino', 'Masculino') NULL,
  `fechaIng` DATE NULL,
  `fechaDiag` DATE NULL,
  PRIMARY KEY (`nomUsuario`),
  INDEX `fk_PACIENTE_ESPECIALISTA1_idx` (`especialista` ASC) VISIBLE,
  INDEX `fk_PACIENTE_CUIDADOR1_idx` (`cuidador` ASC) VISIBLE,
  CONSTRAINT `fk_PACIENTE_ESPECIALISTA1`
    FOREIGN KEY (`especialista`)
    REFERENCES `mydb`.`ESPECIALISTA` (`nomUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_CUIDADOR1`
    FOREIGN KEY (`cuidador`)
    REFERENCES `mydb`.`CUIDADOR` (`nomUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADMINISTRADOR` (
  `nomUsuario` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(70) NULL,
  `contraseña` VARCHAR(45) NULL,
  `correo` VARCHAR(70) NULL,
  PRIMARY KEY (`nomUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AP_SCREENING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AP_SCREENING` (
  `cveAcceso` VARCHAR(10) NOT NULL,
  `paciente` VARCHAR(20) NOT NULL,
  `especialista` VARCHAR(8) NOT NULL,
  `fechaAp` DATE NULL,
  `resultadoFinal` INT NULL,
  PRIMARY KEY (`cveAcceso`),
  INDEX `fk_AP_SCREENING_PACIENTE1_idx` (`paciente` ASC) VISIBLE,
  INDEX `fk_AP_SCREENING_ESPECIALISTA1_idx` (`especialista` ASC) VISIBLE,
  CONSTRAINT `fk_AP_SCREENING_PACIENTE1`
    FOREIGN KEY (`paciente`)
    REFERENCES `mydb`.`PACIENTE` (`nomUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AP_SCREENING_ESPECIALISTA1`
    FOREIGN KEY (`especialista`)
    REFERENCES `mydb`.`ESPECIALISTA` (`nomUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AP_REMINISCENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AP_REMINISCENCIA` (
  `cveAcceso` VARCHAR(10) NOT NULL,
  `paciente` VARCHAR(20) NOT NULL,
  `fechaAp` DATE NULL,
  `resultado` INT NULL,
  PRIMARY KEY (`cveAcceso`),
  INDEX `fk_REMINISCENCIA_PACIENTE1_idx` (`paciente` ASC) VISIBLE,
  CONSTRAINT `fk_REMINISCENCIA_PACIENTE1`
    FOREIGN KEY (`paciente`)
    REFERENCES `mydb`.`PACIENTE` (`nomUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TEMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TEMA` (
  `cveTemas` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(20) NULL,
  `dificultad` ENUM('Facil', 'Medio', 'Dificil') NULL,
  PRIMARY KEY (`cveTemas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENT_COGN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENT_COGN` (
  `cveAcceso` VARCHAR(10) NOT NULL,
  `cveTema` INT NOT NULL,
  `paciente` VARCHAR(20) NOT NULL,
  `fechaAp` DATE NULL,
  `estado` ENUM('Superado', 'No Superado') NULL,
  `tiempo` TIME NULL,
  PRIMARY KEY (`cveAcceso`, `cveTema`),
  INDEX `fk_ENT_COGN_TEMA1_idx` (`cveTema` ASC) VISIBLE,
  INDEX `fk_ENT_COGN_PACIENTE1_idx` (`paciente` ASC) VISIBLE,
  CONSTRAINT `fk_ENT_COGN_TEMA1`
    FOREIGN KEY (`cveTema`)
    REFERENCES `mydb`.`TEMA` (`cveTemas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENT_COGN_PACIENTE1`
    FOREIGN KEY (`paciente`)
    REFERENCES `mydb`.`PACIENTE` (`nomUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MENSAJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MENSAJE` (
  `cveMensaje` INT NOT NULL,
  `especalista` VARCHAR(8) NOT NULL,
  `cuidador` VARCHAR(20) NOT NULL,
  `mensaje` VARCHAR(200) NULL,
  `fechaEnvio` DATE NULL,
  PRIMARY KEY (`cveMensaje`),
  INDEX `fk_MENSAJE_ESPECIALISTA1_idx` (`especalista` ASC) VISIBLE,
  INDEX `fk_MENSAJE_CUIDADOR1_idx` (`cuidador` ASC) VISIBLE,
  CONSTRAINT `fk_MENSAJE_ESPECIALISTA1`
    FOREIGN KEY (`especalista`)
    REFERENCES `mydb`.`ESPECIALISTA` (`nomUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MENSAJE_CUIDADOR1`
    FOREIGN KEY (`cuidador`)
    REFERENCES `mydb`.`CUIDADOR` (`nomUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PALABRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PALABRA` (
  `Tema` INT NOT NULL,
  `cvePalabra` INT NOT NULL AUTO_INCREMENT,
  `palabra` VARCHAR(10) NULL,
  PRIMARY KEY (`Tema`, `cvePalabra`),
  INDEX `fk_PALABRA_TEMA1_idx` (`Tema` ASC) VISIBLE,
  CONSTRAINT `fk_PALABRA_TEMA1`
    FOREIGN KEY (`Tema`)
    REFERENCES `mydb`.`TEMA` (`cveTemas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REMINISCENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REMINISCENCIA` (
  `cveAcceso` VARCHAR(10) NOT NULL,
  `idReactivo` INT NOT NULL,
  `respuestaPaciente` VARCHAR(255) NULL,
  `respuestaCuidador` VARCHAR(255) NULL,
  `valoracion` TINYINT NULL,
  PRIMARY KEY (`cveAcceso`, `idReactivo`),
  INDEX `fk_REMINISCENCIA_PREGUNTAS1_idx` (`idReactivo` ASC) VISIBLE,
  CONSTRAINT `fk_REMINISCENCIA_AP_REMINISCENCIA1`
    FOREIGN KEY (`cveAcceso`)
    REFERENCES `mydb`.`AP_REMINISCENCIA` (`cveAcceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REMINISCENCIA_PREGUNTAS1`
    FOREIGN KEY (`idReactivo`)
    REFERENCES `mydb`.`PREGUNTAS` (`idReactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SCREENING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SCREENING` (
  `idReactivo` INT NOT NULL,
  `cveAcceso` VARCHAR(10) NOT NULL,
  `respuestaT` VARCHAR(100) NULL,
  `respuestaImg` VARBINARY(8000) NULL,
  `puntajeReactivo` INT NULL,
  PRIMARY KEY (`idReactivo`, `cveAcceso`),
  INDEX `fk_SCREENING_AP_SCREENING_idx` (`cveAcceso` ASC) VISIBLE,
  CONSTRAINT `fk_SCREENING_AP_SCREENING`
    FOREIGN KEY (`cveAcceso`)
    REFERENCES `mydb`.`AP_SCREENING` (`cveAcceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PREGUNTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PREGUNTAS` (
  `idReactivo` INT NOT NULL,
  `pregunta` VARCHAR(255) NULL,
  `preguntaBin` VARBINARY(8000) NULL,
  `tipo` ENUM("Texto", "Imagen", "Audio") NULL,
  PRIMARY KEY (`idReactivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REMINISCENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REMINISCENCIA` (
  `cveAcceso` VARCHAR(10) NOT NULL,
  `idReactivo` INT NOT NULL,
  `respuestaPaciente` VARCHAR(255) NULL,
  `respuestaCuidador` VARCHAR(255) NULL,
  `valoracion` TINYINT NULL,
  PRIMARY KEY (`cveAcceso`, `idReactivo`),
  INDEX `fk_REMINISCENCIA_PREGUNTAS1_idx` (`idReactivo` ASC) VISIBLE,
  CONSTRAINT `fk_REMINISCENCIA_AP_REMINISCENCIA1`
    FOREIGN KEY (`cveAcceso`)
    REFERENCES `mydb`.`AP_REMINISCENCIA` (`cveAcceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REMINISCENCIA_PREGUNTAS1`
    FOREIGN KEY (`idReactivo`)
    REFERENCES `mydb`.`PREGUNTAS` (`idReactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
