insert into "Cuidador_cat_pregunta"  values (1,'¿CUál es el nombre de esta canción?', 'AUD', 'OP');
insert into "Cuidador_cat_pregunta"  values (2,'¿A quién le pertenece esta voz?', 'AUD', 'OP');
insert into "Cuidador_cat_pregunta"  values (3,'Esta canción fue muy conocida durante su infancia, ¿Cuál es el nombre de esta canción?', 'AUD', 'OP');
insert into "Cuidador_cat_pregunta"  values (4,'¿Cuál es el título de esta canción?', 'AUD', 'OP');
insert into "Cuidador_cat_pregunta"  values (5,'¿De qué es este sonido?', 'AUD', 'OP');
insert into "Cuidador_cat_pregunta"  values (6,'¿Cuál es el nombre de esta canción?', 'AUD', 'A');
insert into "Cuidador_cat_pregunta"  values (7,'¿Quién canta la siguiente canción?', 'AUD', 'OP');
insert into "Cuidador_cat_pregunta"  values (8,'¿Cuál es el nombre completo de la persona de la fotografía y cuál es su parentesco con ella? Escriba la respuesta en una sola línea, separada por coma y espacio. Ejemplo: ‘Luz López Cano, madre’.', 'IMG', 'A');
insert into "Cuidador_cat_pregunta"  values (9,'¿En dónde fue tomada la siguiente foto?', 'IMG', 'A');
insert into "Cuidador_cat_pregunta"  values (10,'¿Por qué es importante este objeto para usted?', 'IMG', 'A');
insert into "Cuidador_cat_pregunta"  values (11,'¿En qué año trabajó en el siguiente lugar?', 'IMG', 'A');
insert into "Cuidador_cat_pregunta"  values (12,'¿Cómo se llama la persona de la foto?', 'IMG', 'A');
insert into "Cuidador_cat_pregunta"  values (13,'¿En qué año se tomó esta fotografía?', 'IMG', 'A');
insert into "Cuidador_cat_pregunta"  values (14,'¿Quién le regaló este objeto? Escriba nombre', 'IMG', 'A');
insert into "Cuidador_cat_pregunta"  values (15,'¿Quién le escribió esta carta o escrito? Escriba nombre', 'IMG', 'A');
insert into "Cuidador_cat_pregunta"  values (16,'¿A qué época pertenece la ropa que se muestra en la fotografía?', 'IMG', 'A');
insert into "Cuidador_cat_pregunta"  values (17,'¿Identifica la relación entre las dos personas de la fotografía? Por ejemplo, indique si son “Madre e hija”, de entre las opciones propuestas.', 'IMG', 'OP')
insert into "Cuidador_cat_pregunta"  values (18,'¿A qué suceso importante pertenece esta fotografía?', 'IMG', 'OP');
insert into "Cuidador_cat_pregunta"  values (19,'¿En qué año nació?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (20,'¿Cuál es o era el nombre completo de su madre?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (21,'¿Cuál es o era el nombre completo de su padre?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (22,'¿Cuántos hijos tuvo?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (23,'¿En qué año se casó?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (24,'¿Cuál es el nombre de su primera mascota?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (25,'¿Cuántos nietos tiene?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (26,'¿Cuál es el nombre de la última mascota que tuvo o la última que ha adquirido?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (27,'¿Cuál es el nombre completo de su primer hijo/a?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (28,'¿En qué año nació su primer/a hijo/a?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (29,'¿Cuál era su juego favorito durante su infancia?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (30,'¿Cuál era su mayor temor cuando era niño?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (31,'¿A dónde fue en su primer viaje fuera de la Ciudad de México?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (32,'¿Cuál fue el último lugar al que viajó?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (33,'¿Cuál es el nombre completo de su esposo/a?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (34,'¿Cuál es el primer juguete que recuerda haber tenido?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (35,'¿Cuál es su estación del año favorita?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (36,'¿Cuál es su libro favorito?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (37,'¿En qué ciudad reside actualmente?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (38,'¿Cuál fue su primer empleo?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (39,'¿Quién es su autor de libros favorito?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (40,'¿En qué año se estrenó su película favorita?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (41,'¿Cuál es su equipo de fútbol favorito?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (42,'¿Cuál es su banda de música favorita?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (43,'¿En qué año nació su último nieto?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (44,'¿Qué deporte practicaba cuando era joven? Sólo una opción es correcta.', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (45,'¿Qué quería ser de grande cuando era niño?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (46,'¿Qué canción bailó en su boda como primer baile de esposos?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (47,'¿En qué año se jubiló?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (48,'¿En que trabajó? Sólo una opción es correcta.', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (49,'¿Cuál era el nombre completo de su abuelo paterno?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (50,'¿En qué año comenzó a trabajar?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (51,'¿En dónde fue su primer trabajo?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (52,'¿Cuál es el nombre de su hermano/a mayor?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (53,'¿Cuántos hermanos tiene?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (54,'¿Qué es lo primero que hace al despertar?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (55,'¿Cuál es su género de películas favorito?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (56,'¿Cuál es el género de música que usted más escucha?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (57,'¿A dónde se fue de luna de miel?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (58,'¿Qué es lo último que hace antes de dormir?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (59,'¿Qué película estaba de moda en los años 60’s?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (60,'¿Cuál era su materia favorita en la primaria?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (61,'¿Cuál es su instrumento musical favorito?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (62,'¿A qué animal le tiene más miedo?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (63,'¿Cuál es el nombre de su mejor amigo de la infancia?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (64,'¿Cuál es su planta favorita?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (65,'Seleccione el nombre que pertenezca a un integrante de su familia', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (66,'¿Cuál era el nombre de su abuela materna?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (67,'¿En dónde se encontraba durante el temblor de 1985?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (68,'¿Cuál es su platillo de comida favorito?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (69,'¿Cuál es su postre favorito?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (70,'¿Cuál es su color favorito?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (71,'¿En qué año conoció al amor de su vida?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (72,'¿Cuántos años tiene?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (73,'¿Cuál era un juego que más jugaba durante su infancia?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (74,'¿En qué ciudad vive actualmente?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (75,'¿Con quién vive actualmente? Escriba solo parentesco separado por coma y espacio.', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (76,'¿Quién cuida de usted? Escriba solo el parentesco.', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (77,'¿Cuál fue su primer trabajo?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (78,'¿En dónde vivió durante su infancia?', 'TXT', 'A');
insert into "Cuidador_cat_pregunta"  values (79,'¿En qué año se descubrió América?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (80,'¿En qué año terminó la Segunda Guerra Mundial?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (81,'¿En qué año se cayeron las torres gemelas?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (82,'¿Qué actores eran famosos en la época de oro mexicano?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (83,'¿En qué año comenzó la Primera Guerra Mundial?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (84,'¿En qué año fue el mayor terremoto en México?', 'TXT', 'OP');
insert into "Cuidador_cat_pregunta"  values (85,'¿Qué día se celebra Noche Buena?', 'TXT', 'OP');
