# Generated by Django 3.1.7 on 2021-03-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Especialista', '0001_initial'),
        ('Cuidador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ap_Reminiscencia',
            fields=[
                ('cveAcceso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fechaAp', models.DateField()),
                ('resultadoFinal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idReactivo', models.IntegerField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('tipo', models.CharField(choices=[('TXT', 'Texto'), ('IMG', 'Imagen'), ('AUD', 'Audio')], max_length=50)),
                ('preguntaBin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('cveTemas', models.IntegerField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=20)),
                ('dificultad', models.CharField(choices=[('F', 'Facil'), ('M', 'Medio'), ('D', 'Dificil')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idReactivo', models.IntegerField()),
                ('respuestaT', models.CharField(max_length=100)),
                ('respuestaImg', models.ImageField(upload_to='')),
                ('puntajeReactivo', models.IntegerField()),
                ('puntajeMaximo', models.IntegerField()),
                ('cveAcceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pruebas.ap_reminiscencia')),
            ],
        ),
        migrations.CreateModel(
            name='Reminiscencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestaPaciente', models.CharField(max_length=255)),
                ('respuestaCuidador', models.CharField(max_length=255)),
                ('resultado', models.IntegerField()),
                ('cveAcceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pruebas.ap_reminiscencia')),
                ('idReactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pruebas.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('cvePalabra', models.IntegerField(primary_key=True, serialize=False)),
                ('palabra', models.CharField(max_length=10)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pruebas.tema')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nomUsuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('contraseña', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('escolaridad', models.CharField(choices=[('N', 'Ninguna'), ('PR', 'Primaria'), ('SC', 'Secundaria'), ('BCH', 'Bachillerato'), ('SUP', 'Licenciatura o superior')], max_length=50)),
                ('fechaNac', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=50)),
                ('fechaIng', models.DateField()),
                ('fechaDiag', models.DateField()),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuidador.cuidador')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Especialista.especialista')),
            ],
        ),
        migrations.CreateModel(
            name='Ent_Cogn',
            fields=[
                ('cveAcceso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('S', 'Superado'), ('NS', 'No superado')], max_length=50)),
                ('cveTema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pruebas.tema')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pruebas.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Ap_Screening',
            fields=[
                ('cveAcceso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fechaAp', models.DateField()),
                ('resultadoFinal', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pruebas.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='ap_reminiscencia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pruebas.paciente'),
        ),
    ]
