# Generated by Django 3.1.3 on 2021-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ap_reminiscencia',
            name='reminiscencia',
            field=models.ManyToManyField(through='Pruebas.Reminiscencia', to='Pruebas.Pregunta'),
        ),
    ]
