# Generated by Django 3.1.3 on 2021-04-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuidador', '0001_initial'),
        ('Especialista', '0002_auto_20210414_2058'),
        ('Pruebas', '0001_initial'),
    ]

    operations = [
         migrations.CreateModel(
            name='Reminiscencia',
            fields=[
                ('idApp', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('respuestaPaciente', models.CharField(max_length=255)),
                ('valoracion', models.BooleanField()),
                ('cveAcceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idRem', to='Pruebas.ap_reminiscencia')),
                ('idPregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idRem', to='Cuidador.pregunta')),
            ],
        ),
    ]
