# Generated by Django 3.1.3 on 2021-03-09 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminiscencia',
            name='id',
        ),
        migrations.AlterField(
            model_name='reminiscencia',
            name='cveAcceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='idRem', serialize=False, to='Pruebas.ap_reminiscencia'),
        ),
    ]
