# Generated by Django 3.1.3 on 2021-03-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='palabra',
            unique_together={('cvePalabra', 'tema')},
        ),
    ]
