# Generated by Django 3.1.3 on 2021-03-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap_reminiscencia',
            name='cveAcceso',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
