# Generated by Django 3.1.3 on 2021-03-08 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ap_reminiscencia',
            name='reminiscencia',
            field=models.ManyToManyField(related_name='aps', through='Pruebas.Reminiscencia', to='Pruebas.Pregunta'),
        ),
        migrations.AlterField(
            model_name='reminiscencia',
            name='cveAcceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_reminiscencia', to='Pruebas.ap_reminiscencia'),
        ),
        migrations.AlterField(
            model_name='reminiscencia',
            name='idReactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_reminiscencia', to='Pruebas.pregunta'),
        ),
    ]
