# Generated by Django 3.1.3 on 2021-03-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0002_auto_20210308_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screening',
            options={},
        ),
    ]
