# Generated by Django 3.1.3 on 2021-03-08 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0003_auto_20210308_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='cveAcceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pruebas.ap_screening'),
        ),
        migrations.AlterUniqueTogether(
            name='screening',
            unique_together={('cveAcceso', 'idReactivo')},
        ),
    ]
