# Generated by Django 3.1.3 on 2021-03-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0003_auto_20210309_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='preguntaBin',
            field=models.BooleanField(null=True),
        ),
    ]
