# Generated by Django 3.1.3 on 2021-03-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0004_auto_20210308_2303'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='screening',
            table=None,
        ),
    ]
