# Generated by Django 3.1.3 on 2021-03-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0004_auto_20210321_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='preguntaBin',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='preguntaImg',
            field=models.BinaryField(null=True),
        ),
    ]
