# Generated by Django 3.1.3 on 2021-03-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0005_auto_20210308_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminiscencia',
            name='cveAcceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_remi', to='Pruebas.ap_reminiscencia'),
        ),
        migrations.AlterField(
            model_name='reminiscencia',
            name='idReactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_remi', to='Pruebas.pregunta'),
        ),
    ]
