# Generated by Django 3.1.3 on 2021-03-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0010_auto_20210308_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminiscencia',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
