# Generated by Django 3.1.3 on 2021-03-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0011_auto_20210308_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminiscencia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
