# Generated by Django 3.1.3 on 2021-03-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('nomUsuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('contraseña', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
