# Generated by Django 3.1.3 on 2021-03-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuidador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='preguntaAu',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='preguntaImg',
            new_name='imagen',
        ),
    ]
