# Generated by Django 3.1.3 on 2021-03-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Cuidador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='nomUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Usuarios.usuario'),
        ),
    ]
