# Generated by Django 3.1.3 on 2021-03-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuidador', '0002_auto_20210310_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='contraseña',
            field=models.CharField(max_length=45),
        ),
    ]
