# Generated by Django 3.1.3 on 2021-03-16 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuidador', '0003_auto_20210311_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuidador',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
