# Generated by Django 3.1.3 on 2021-03-16 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cuidador', '0004_auto_20210316_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='highlighted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuidadores', to=settings.AUTH_USER_MODEL),
        ),
    ]
