# Generated by Django 3.1.3 on 2021-03-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuidador', '0005_auto_20210316_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='owner',
        ),
    ]
