# Generated by Django 2.2.12 on 2021-05-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Pregunta',
            fields=[
                ('idReactivo', models.IntegerField(primary_key=True, serialize=False)),
                ('reactivo', models.TextField()),
                ('tipoDato', models.CharField(choices=[('TXT', 'Texto'), ('IMG', 'Imagen'), ('AUD', 'Audio')], max_length=50)),
                ('tipoPregunta', models.CharField(choices=[('A', 'Abierta'), ('OP', 'Opcion Multiple')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reminiscencia')),
                ('audio', models.FileField(blank=True, null=True, upload_to='reminiscencia')),
                ('respuestaCuidador', models.CharField(max_length=255)),
                ('idCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Cuidador')),
                ('idReactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuidador.Cat_Pregunta')),
            ],
        ),
    ]
