# Generated by Django 3.1.7 on 2021-03-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuidador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('nomUsuario', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('contrasena', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('numPacientes', models.IntegerField()),
                ('datos_generales', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('cveMensaje', models.IntegerField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=200)),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuidador.cuidador')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Especialista.especialista')),
            ],
        ),
    ]
