# Generated by Django 3.1.7 on 2021-04-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Especialista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='datos_generales',
            field=models.CharField(default='Escribe aquí información que consideres importante', max_length=200),
        ),
    ]
