# Generated by Django 3.1.7 on 2021-04-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Especialista', '0002_auto_20210416_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='datos_generales',
            field=models.CharField(max_length=200),
        ),
    ]
