# Generated by Django 3.1.3 on 2021-05-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ent_cogn',
            name='cveAcceso',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
