# Generated by Django 3.1.3 on 2021-05-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='respuestaT',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
