# Generated by Django 3.1.3 on 2021-05-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_auto_20210504_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap_screening',
            name='resultadoFinal',
            field=models.IntegerField(null=True),
        ),
    ]
