# Generated by Django 3.1.3 on 2021-05-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_auto_20210508_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palabra',
            name='idPalabra',
        ),
        migrations.AlterField(
            model_name='palabra',
            name='cvePalabra',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
