# Generated by Django 3.1.7 on 2021-04-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nomUsuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('contrasena', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
