# Generated by Django 3.1.3 on 2021-03-16 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='contrasena',
            new_name='contraseña',
        ),
    ]
